import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ThemedButton from './blog/darkMode'
import Footer from './footer'
import Header from './header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}

        <Footer />
      </body>
    </html>
  )
}
